### ISSUE TITLE
Retrieving additional properties on deals

### ISSUE THREAD

**Issue by zimmerel** [jpetrucciani/hubspot3#14]
Hi, I noticed there isn't an obvious way (to me at least) to conveniently request additional properties when requesting bulk deals. I came accross this using the `DealsClient.get_all()` method. For now, I am getting around this by building a query string manually and passing it to the method as `query=&property=property1`.

It seems to me that there should be some way of expanding the requested properties in the method. I could play around with adding this functionality when I have a bit more time.

Of course, if there is a way to do this that I'm completely missing, I'd love to hear about it.

**Comment by jpetrucciani** [comment]
I'll be sure to let you know when I've got some of that functionality ready!

Absolutely! Feel free to make PR's for anything you think others may find useful (additional endpoints are awesome)! It makes the library better for us all 😄

**Comment by jpetrucciani** [comment]
I've added some basic support for this now, available as a keyword argument on the `DealsClient.get_all` method!
https://github.com/jpetrucciani/hubspot3/releases/tag/3.1.6

It is now live on pip as well as version `3.1.6`
