### ISSUE TITLE
Delete company

### ISSUE THREAD

**Issue by SioKCronin** [jpetrucciani/hubspot3#19]
Hi Jacobi,

Thanks so much for sharing this great project!

I've identified some companies I'd like to delete from Hubspot, and would like to extend the Company client to support it. I found [this documentation](https://developers.hubspot.com/docs/methods/companies/delete_company), and am putting together a PR now :)

**Comment by jpetrucciani** [comment]
Thanks for the kind words!

Awesome - #20 looks good to me, I'll get it merged in soon!

**Comment by jpetrucciani** [comment]
This is now included in version `3.2.1` on pip! I'll close the issue for now, but feel free to reopen it if you have any issues!
