### ISSUE TITLE
CRM Associations

### ISSUE THREAD

**Issue by SioKCronin** [jpetrucciani/hubspot3#23]
Hi Jacobi,

Our team has requested support for CRM Associations (child company to parent companies). I'm going test a local prototype this week and aim to propose a PR here to roll it in. 

I had thought it would just involve updating a company property, but it has its own endpoint: https://developers.hubspot.com/docs/methods/crm-associations/associate-objects

Adding this issue in case someone wants to team up on this :) 

Cheers,

Siobhán

**Comment by jpetrucciani** [comment]
Sounds awesome!

**Comment by zimmerel** [comment]
I actually have a commit for crm associations that I've been hoarding all to myself. 

I've mostly just been too busy to finish it and submit a pr, but it is almost done so I may as well get it finished and submit it. I only have done get and create methods though.

**Comment by tornikenats** [comment]
I've created a pr inspired by @zimmerel and @fairtax: https://github.com/jpetrucciani/hubspot3/pull/27

**Comment by jpetrucciani** [comment]
I've got @tornikenats's PR merged in (it has `get`, `get_all`, `create`, and `delete`), now on pip as version `3.2.5`. I'll go ahead and close this issue for now, but feel free to reopen!
