### ISSUE TITLE
Readme API Limits

### ISSUE THREAD

**Issue by zimmerel** [jpetrucciani/hubspot3#57]
I just wanted to put in an issue for the readme API limits. They were recently updated:
https://developers.hubspot.com/apps/api_guidelines

It's not terribly important, but just wanted to get it on the radar.

**Comment by jpetrucciani** [comment]
Good call! I can update these in just a bit, unless you've got plans to do so in a PR!

**Comment by zimmerel** [comment]
Sorry, just saw this. I just went ahead and did it real quick. I just submitted the PR.

**Comment by jpetrucciani** [comment]
Merged - Thanks for the contribution!
