### ISSUE TITLE
Use Requests

### ISSUE THREAD

**Issue by kylecribbs** [jpetrucciani/hubspot3#77]
I think it would be better to use requests library instead of making your own off of urllib. There is an endpoint for uploading files that needs to be multi-part. Your current library will not support and will consider a re-write. Probably better to just use requests as most of this stuff is built in.

**Comment by jpetrucciani** [comment]
I'll definitely consider that when the time comes to implement such functionality! For right now, this accomplishes what we need

As of right now, this library has no dependencies at all (unless you want the CLI functionality).

In the meantime, if you'd like this functionality, feel free to fork and experiment with adding it!
