### ISSUE TITLE
Engagement API, function get_associated contains two print statements

### ISSUE THREAD

**Issue by henrik-berglund** [jpetrucciani/hubspot3#91]
Hi,

Sorry if I misunderstood, but I get some printouts when running and suspect it is these two print statements doing it:

while not finished:
            print(offset)
            batch = self._call(
                "engagements/associated/{}/{}/paged".format(object_type, object_id),
                method="GET",
                params={"limit": query_limit, "offset": offset},
                **options
            )
            print(len(batch["results"]))

**Comment by jpetrucciani** [comment]
Good catch! I'll get those removed. Thanks for bringing this up!

**Comment by jpetrucciani** [comment]
This should now be live on pip as version [`3.2.44`](https://github.com/jpetrucciani/hubspot3/releases/tag/3.2.44)!
