### ISSUE TITLE
get_all() fails 

### ISSUE THREAD

**Issue by corrigantj** [jpetrucciani/hubspot3#99]
thanks for writing this. trying to use for some quick api prototyping.

when trying the quickstart guide, i get the following error.

(Python 3.8.2)

![Screen Shot 2020-05-14 at 11 39 31 AM](https://user-images.githubusercontent.com/1121366/81972691-d27aec80-95d7-11ea-8dc8-fc279e011eb3.png)

**Comment by jpetrucciani** [comment]
Hmm, appears to be SSL cert related - what OS are you on?

**Comment by jpetrucciani** [comment]
Looks like mac - if so, could you check [this stackoverflow](https://stackoverflow.com/a/58525755/6650640) out?

**Comment by corrigantj** [comment]
this totally worked. thanks for helping this noob PM.

**Comment by jpetrucciani** [comment]
Glad to help! 😄
